### ISSUE TITLE
Developmnet

### ISSUE THREAD

**Issue by carnesen** [calebmer/node_modules#4]
Hello. Thanks for this repo. I've been struggling with the one-repo-per-package approach, and I'm going to give this architecture a try. FYI I noticed a typo in several places here, "developmnet" => "development", though it shouldn't really matter because any non-"production" value of NODE_ENV is typically interpreted as "development".

**Comment by calebmer** [comment]
Thanks for the message! The current architecture is based off what was easiest to me a couple months ago. Soon I'm going to try moving to [lerna](https://www.npmjs.com/package/lerna) instead of custom scripts (or write a meta package that encapsulates the scripts I currently use (in the `_scripts` folder). I'm also probably going to either entirely replace Babel with TypeScript, or at least make TypeScript optional as I'm really enjoying working with it.

The greatest advantage of this architecture though is being able to use this repo as a self-updating resume.

Best of luck implementing this architecture, and tell me what you learn from it! 😊
